<a href="https://colab.research.google.com/github/JaviSantosM/Economia3/blob/main/Clase04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math

In [3]:
from math import sqrt,pi

In [4]:
pi

3.141592653589793

In [5]:
import math as m

In [6]:
m.log(10)

2.302585092994046

In [7]:
m.pow(2,3)#x^n=pow(x,n)

8.0

In [8]:
m.factorial(5)

120

In [9]:
m.sin(pi/2)

1.0

In [10]:
import random

In [11]:
random.randint(1,100)

77

In [12]:
random.uniform(0,1)

0.011253350945977014

In [13]:
random.choice(['A','B','C','D'])

'A'

In [15]:
from datetime import datetime, timedelta

In [16]:
datetime.now()

datetime.datetime(2026, 2, 4, 21, 27, 40, 848277)

In [17]:
hora_actual=datetime.now()

In [19]:
hora_actual+timedelta(days=10)

datetime.datetime(2026, 2, 14, 21, 29, 46, 317604)

In [22]:
hora_actual+timedelta(days=10,weeks=1)

datetime.datetime(2026, 2, 21, 21, 29, 46, 317604)

In [23]:
import os
import sys

In [24]:
os.getcwd()

'/content'

In [25]:
os.name

'posix'

In [26]:
sys.version<m

'3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]'

In [27]:
import numpy as np

In [29]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [31]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr3=np.array([[[1,2],[3,4],[5,6]]])
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones(4)

array([1., 1., 1., 1.])

In [38]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.random.rand(3,3)

array([[0.59957314, 0.09092598, 0.61148387],
       [0.05755332, 0.78432861, 0.56915614],
       [0.59145048, 0.67643273, 0.49765555]])

In [40]:
np.linspace(0,10,5)#inicio,fin,cantidad de puntos de los intervalos

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
arr=np.array([1,2,3,4,5,6])

In [42]:
arr[1]

np.int64(2)

In [43]:
a=np.array([1,2,3])

In [44]:
b=np.array([4,5,6])

In [45]:
a+b

array([5, 7, 9])

In [46]:
b-a

array([3, 3, 3])

In [48]:
a*b

array([ 4, 10, 18])

In [50]:
b/a

array([4. , 2.5, 2. ])

In [51]:
arr1=np.array([0,np.pi/2,np.pi])

In [52]:
np.sin(arr1)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [53]:
np.cos(arr1)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [55]:
np.log(arr1+1)

array([0.        , 0.94421571, 1.42108041])

In [56]:
arr=np.array([10,20,30,40,50])

In [57]:
np.mean(arr)

np.float64(30.0)

In [58]:
np.median(arr)

np.float64(30.0)

In [59]:
np.std(arr)

np.float64(14.142135623730951)

In [60]:
np.var(arr)

np.float64(200.0)

In [61]:
np.min(arr)

np.int64(10)

In [62]:
np.max(arr)

np.int64(50)

In [63]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,9]])

In [64]:
B-A

array([[4, 4],
       [4, 5]])

In [65]:
A*B

array([[ 5, 12],
       [21, 36]])

In [66]:
np.matmul(A,B)

array([[19, 24],
       [43, 54]])

In [67]:
A@B

array([[19, 24],
       [43, 54]])

In [68]:
np.dot(A,B)

array([[19, 24],
       [43, 54]])

In [69]:
np.cross(A,B)

/tmp/ipython-input-3729917815.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(A,B)


array([-4, -1])

In [71]:
from numpy.linalg import det, inv

In [72]:
det(A)

np.float64(-2.0000000000000004)

In [73]:
A

array([[1, 2],
       [3, 4]])

In [74]:
inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [75]:
np.matmul(A,inv(A))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [76]:
A.T

array([[1, 3],
       [2, 4]])

In [78]:
from numpy.linalg import eig

In [79]:
M=np.array([[2,-1],[-1,2]])

In [81]:
eigenvalores,eigenvectores=eig(M)

eigenvalores

array([3., 1.])

In [82]:
eigenvectores

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

Normas

In [85]:
v=np.array([3,4])
v

array([3, 4])

In [86]:
norma_l2=np.linalg.norm(v)
norma_l2

np.float64(5.0)

In [ ]:
#Norma l1, Norma Manhattan

In [88]:
n_l1=np.linalg.norm(v,ord=1)
n_l1

np.float64(7.0)

In [89]:
np.linalg.norm(v,ord=np.inf)

np.float64(4.0)

Pandas

In [90]:
import pandas as pd

In [92]:
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [93]:
pd.DataFrame([10,20,30,40,50])

0
0  10
1  20
2  30
3  40
4  50

In [96]:
data=[1,2,3,4,5,6,7]
pd.DataFrame(data,columns=['Numeros'],index=['Lunes','Martes','Miercoles','J','V','S','D'])

Numeros
Lunes            1
Martes           2
Miercoles        3
J                4
V                5
S                6
D                7

In [101]:
data=[['JAVI',21],['Alexis',21],['Derek',22]]
df=pd.DataFrame(data)
df

0   1
0    JAVI  21
1  Alexis  21
2   Derek  22

In [103]:
datos={
    'Nom':['Alexis','Axel','Derek','Javi'],
    'Sexo':['H','H','H','H'],
    'Calif':[10,9,8,7]
}
pd.DataFrame(datos)

Nom Sexo  Calif
0  Alexis    H     10
1    Axel    H      9
2   Derek    H      8
3    Javi    H      7

In [104]:
import yfinance as yf

In [107]:
df_aapl=yf.download('AAPL',start="2024-01-01", end='2026-01-01')
df_aapl

/tmp/ipython-input-491110574.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_aapl=yf.download('AAPL',start="2024-01-01", end='2026-01-01')
[*********************100%***********************]  1 of 1 completed


Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date                                                                
2024-01-02  183.903229  186.677036  182.169601  185.399096  82488700
2024-01-03  182.526230  184.140985  181.713894  182.496512  58414500
2024-01-04  180.208115  181.377068  179.187752  180.445860  71983600
2024-01-05  179.484955  181.050175  178.484409  180.287390  62379700
2024-01-08  183.823975  183.863609  179.801961  180.386437  59144500
...                ...         ...         ...         ...       ...
2025-12-24  273.809998  275.429993  272.200012  272.339996  17910600
2025-12-26  273.399994  275.369995  272.859985  274.160004  21521800
2025-12-29  273.760010  274.359985  272.350006  272.690002  23715200
2025-12-30  273.079987  274.079987  272.279999  272.809998  22139600
2025-12-31  271.859985  273.679993  271.750000  273.059998  27293600

[502 rows x 5 columns]

In [108]:
df_aapl.to_excel("finanzas_apple.xlsx")

In [115]:
df_aapl.to_csv("finanzas_apple.csv")

In [114]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
